# Generated by Django 2.1.2 on 2018-11-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181028_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment',
        ),
    ]
