# Generated by Django 2.1.2 on 2018-11-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181104_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='content',
        ),
    ]
