# Generated by Django 2.1.2 on 2018-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20181104_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ForeignKey(default=1, on_delete='', to='books.Comments'),
            preserve_default=False,
        ),
    ]
