# Generated by Django 2.1.2 on 2018-11-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
    ]
