# Generated by Django 2.1.2 on 2018-11-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
