# Generated by Django 2.1.2 on 2018-11-07 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_book_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_reaction',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
