# Generated by Django 2.1.2 on 2018-11-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_user_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_likes',
        ),
    ]
