# Generated by Django 2.1.2 on 2018-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_likes',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
