# Generated by Django 2.1.2 on 2018-11-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20181107_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_likes',
        ),
    ]
