# Generated by Django 2.1.2 on 2018-11-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_likes',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
