# Generated by Django 2.1.2 on 2018-11-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_likes',
        ),
    ]
