# Generated by Django 2.1.2 on 2018-11-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_book_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_likes',
            field=models.FloatField(default=0),
        ),
    ]
