# Generated by Django 2.1.2 on 2018-11-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
