# Generated by Django 2.1.2 on 2018-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20181118_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
