# Generated by Django 2.1.2 on 2018-11-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20181118_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='count',
        ),
    ]
