# Generated by Django 2.1.2 on 2018-11-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_remove_useraccount_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
